### ISSUE TITLE
Sending bridged DOT from AH to parachain fails after upgrade

### ISSUE THREAD

**Issue by olanod** [polkadot-fellows/runtimes#281] opened 2024-04-21 20:16 UTC
Before the last upgrade at block [6793666](https://assethub-kusama.subscan.io/extrinsic/6793666-2) there's an example of a *limited reserve transfer assets* of DOT from Kusama asset hub to parachain `2281` which was successful, after the upgrade we can see another example at block [6814790](https://assethub-kusama.subscan.io/extrinsic/6814790-2) which fails with the error `InvalidAssetUnknownReserve`. It seems like a regression unless sending such foreign asset to a Kusama parachain is expected to be done differently now.

**Comment by joepetrowski** [comment] 2024-04-22 04:48
@acatangiu @franciscoaguirre

**Comment by acatangiu** [comment] 2024-04-22 11:25
Yes, it is an unintended regression.

The fact that we could do it before the upgrade with the old extrinsic was just "lucky". Once on the parachain, the extrinsic could not send it anywhere else (not even back).

The currently deployed runtime includes https://github.com/paritytech/polkadot-sdk/pull/1672 and https://github.com/paritytech/polkadot-sdk/pull/2388 which allow transfers of foreign assets in all directions within same consensus.

Unfortunately, for bridged assets the "smart logic" added to the extrinsics in above PRs doesn't work anymore because the code cannot determine anymore which chain on this side of the bridge is allowed to act as a reserve for an asset on the other side of the bridge.

For moving bridged assets around I created a new extrinsic https://github.com/paritytech/polkadot-sdk/pull/3695 that allows the caller to force/override/specify reserve locations for "exotic" assets (where such information is not available in the runtime). I am also pushing for an offchain asset registry to hold this information: https://forum.polkadot.network/t/xcm-asset-registry/1168/3.
Unfortunately, https://github.com/paritytech/polkadot-sdk/pull/3695 did not make it into AH 1.2.0 runtimes, but I plan to add it very soon in a AH runtime "patch upgrade".

**Comment by olanod** [comment] 2024-05-13 08:32
@acatangiu will this be possible already in 1.2.2 ? how would the transfer extrinsic look like?

**Comment by acatangiu** [comment] 2024-05-13 09:10
> will this be possible already in 1.2.2 ?

Not possible yet in 1.2.2, I see on https://github.com/polkadot-fellows/runtimes/releases/ that 1.2.1, 1.2.2 and 1.2.3 were patch releases for other chains for other issues. Asset Hub runtimes latest release is still 1.2.0.

I'll try to get it in https://github.com/polkadot-fellows/runtimes/issues/288, but I can't promise I'll make it (many things on my plate).
You can try to do it yourself too (backport this new method from latest `pallet-xcm` to whatever `pallet-xcm` version was used in 1.2.0 - this can help you easily find which versions used where https://github.com/paritytech/psvm).

> how would the transfer extrinsic look like?

Example [test for bridged asset AssetHub->Parachain](https://github.com/paritytech/polkadot-sdk/blob/e0584a153df63ff138d12764085422ed06de548a/cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/hybrid_transfers.rs#L150C1-L156C54) - the actual call used [here](https://github.com/paritytech/polkadot-sdk/blob/e0584a153df63ff138d12764085422ed06de548a/cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/hybrid_transfers.rs#L57C1-L70C3).
Example [test for bridged asset Parachain->AssetHub](https://github.com/paritytech/polkadot-sdk/blob/e0584a153df63ff138d12764085422ed06de548a/cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/hybrid_transfers.rs#L278C1-L285C54) - the actual call used [here](https://github.com/paritytech/polkadot-sdk/blob/e0584a153df63ff138d12764085422ed06de548a/cumulus/parachains/integration-tests/emulated/tests/assets/asset-hub-westend/src/tests/hybrid_transfers.rs#L76C2-L89C3).

In general, the emulated tests should cover all transfers scenarios and showcase how to do anything. Please let me know if you have a scenario not covered there.

**Comment by acatangiu** [comment] 2024-05-15 15:49
Backported for upcoming release: https://github.com/polkadot-fellows/runtimes/pull/311

**Comment by acatangiu** [comment] 2024-06-03 15:50
@olanod following the [v1.2.4 upgrade](https://kusama.polkassembly.io/referenda/400), you can now do this with the following xt:

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc-asset-hub-kusama.luckyfriday.io#/extrinsics/decode/0x1f0d03010100a523030400020109020002286bee010300020109020103040d0102040001010068170716ab7c6735dd0a1012045d9ea33891b5f6596cf97eb217d0962d86a51800

Please confirm it works for you too.

**Comment by acatangiu** [comment] 2024-10-14 12:34
this is fixed, @olanod or @bkchr please close it

**Closed** 2024-10-14 13:54 UTC
