### ISSUE TITLE
[ci] `arduino/setup-protoc@v1` API rate limit exceeded for 52.238.27.195

### ISSUE THREAD

**Issue by bkontur** [polkadot-fellows/runtimes#144] opened 2024-01-15 15:12 UTC
E.g,: [ failed job](https://github.com/polkadot-fellows/runtimes/actions/runs/7530536409/job/20497157246?pr=137&step=4)
```
Error: Error: API rate limit exceeded for 52.238.27.195. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
```
We use this for [`check-migrations.yml`](https://github.com/polkadot-fellows/runtimes/blob/main/.github/workflows/check-migrations.yml#L53-L56) and runtime-matrix will just grow with adding new SP runtimes (e.g. people, coretime, ...).

How to fix?  Add that authentication? Or install some prerequisites just once before matrix job runs (not sure if possible)?

I guess, we need that `protoc` or can be removed?

**Comment by ggwpez** [comment] 2024-01-15 17:17
duplicate of https://github.com/polkadot-fellows/runtimes/issues/136

>I guess, we need that protoc or can be removed?

Substrate wont build without.

**Closed** 2024-01-15 18:11 UTC
