### ISSUE TITLE
[CI] Publish unoptimized runtime blobs for debugging

### ISSUE THREAD

**Issue by kianenigma** [polkadot-fellows/runtimes#377] opened 2024-07-08 11:46 UTC
This is a request to publish each runtime with two properties: 

- Add `--features try-runtime`
- Do NOT add `--features on-chain-release-build`: 

https://github.com/polkadot-fellows/runtimes/blob/40f849df87a8a1b79aba4cfb7ce762d868243dca/.github/workflows/release.yml#L59

The former does nothing particular, but it adds a few extra runtime apis that can be used to test the runtime with a tool in the try-runtime family. 

The latter will impact the wasm blob and enable all the runtime logging. This will slightly reduce performance. 

These wasm blobs will then allow 3rd party teams, including Parity to run better monitoring nodes. 

If done by someone familiar with the fellowship CI/release, I'd be happy to complement this work by providing a detailed guide on how to use these blobs to do better monitoring with these notes. 

@liamaharon you might know any prior attempt at this, if any?

**Comment by xlc** [comment] 2024-07-08 11:50
This will be very useful to debug chains with Chopsticks. I had multiple occurrences that I need to make such debug build to figure out why some XCM fails on relaychain/system parachain.

**Comment by bkchr** [comment] 2024-08-12 14:03
Duplicate of: https://github.com/polkadot-fellows/runtimes/issues/268

**Closed by bkchr** 2024-08-12 14:03 UTC
